application: supersimplechess
version: 2
runtime: python
api_version: 1

handlers:
#- url: /
  #script: home.py

#- url: /index\.html
  #script: home.py

#- url: /(.*\.(gif|png|jpg))
  #static_files: static/\1
  #upload: static/(.*\.(gif|png|jpg))

- url: /api/.*
  script: app.py

- url: (/?.*)/
  static_files: static\1/index.html
  upload: static(.*)/index.html

- url: /
  static_dir: static
